### ISSUE TITLE
Add the ability to perform net coverage on `interfaceProperties`

### ISSUE THREAD

**Issue by rickdonato** [UWNetworksLab/netcov#15]
It would be great to add the ability to perform net coverage on the `interfaceProperties` question.

**Comment by ratulm** [comment]
@rickdonato - we'll look into it. 

what would you like the semantics to be -- all interfaces returned by the question are deemed covered?

**Comment by rickdonato** [comment]
Thanks @ratulm yep that would be good. Though would it be poss to only indenify certain coverage for certain fields that queried. i.e. using either of the following would cover the MTU settings for the interfaces. Further more if you filtered down the interfaces for certain nodes or interfaces on a node then the coverage would also represent that.

```
bf.q.interfaceProperties().answer().frame().MTU
bf.q.interfaceProperties(properties="MTU").answer().frame()
```

Thanks again,

**Comment by ratulm** [comment]
Field-level precision won't be possible in the short term. Batfish doesn't maintain that granularity.

But this should be possible, if you filtered using the nodes/interfaces parameters of the question.
> Further more if you filtered down the interfaces for certain nodes or interfaces on a node then the coverage would also represent that.

@Ashlippers - does that sound right? doable for you?

**Comment by xieyangxu** [comment]
@rickdonato Hi Rick, we are glad to inform you that coverage support for `interfaceProperties` has now been added. Due to the limit of Batfish data model, the coverage of interfaces is now defined at interface level, not field level. It means an interface is covered when ANY of its field is queried.
