### ISSUE TITLE
For Batfish configuration can we please add VXLAN related configuration. 

### ISSUE THREAD

**Issue by magrewal** [UWNetworksLab/netcov#23]
Hi Team
For Batfish configuration can we please add VXLAN related configuration. 
configuration related to NVE interface, evpn routes etc.

Checked on below link dont see configuration related to VXLAN EVPN

https://pybatfish.readthedocs.io/en/latest/notebooks/configProperties.html

**Comment by ratulm** [comment]
@magrewal - can you say a bit more about your use case? I am especially curious what types of tests you are running that you'd like to map back to VXLAN configuration.

**Comment by magrewal** [comment]
hi @ratulm 
Various test which we are running are below which we would like to map with Vxlan configuration
Shut and No Shut Nve Interface
Remove Add L2vni Under NveInterface
Remove Add L3vni Under NveInterface
Remove Add Nve Source Interface
Disable Enable NvOverlay Evpn

**Comment by ratulm** [comment]
Looks like your question/request is about Batfish, not NetCov. 

Batfish has these questions related to Vxlan: https://pybatfish.readthedocs.io/en/latest/notebooks/vxlan_evpn.html

I am closing the issue here. If I misunderstood your intent, feel free to open it back.
